language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - time sudo apt-get update -qq
  - pip install pipenv --upgrade
  - pipenv install --dev

script:
  - pipenv run py.test tests

after_success:
  - coveralls
