language: python
python:
  - 2.7
  - 3.5
  - 3.6

before_install:
  - time sudo apt-get update -qq
  - pip install pipenv --upgrade

install:
  - pipenv install --dev --skip-lock

script:
  - pipenv run py.test tests --cov=pysortexif

after_success:
  - coveralls
