language: python
python:
  - 2.7
  - 3.3
  - 3.4

install:
  - time sudo apt-get update -qq
  - pip install pyenv --upgrade
  - pipenv install --dev

script:
  - pipenv run py.test tests

after_success:
  - coveralls
